export const Events =
[
	{
		allDay: false,
		start: new Date('February 16, 2022 10:00'),
		end: new Date('February 16, 2022'),
		title: 'Fulton County Jail Facilitation',
		location: '',
	},
	{
		allDay: true,
		start: new Date('February 23, 2022 10:00'),
		end: new Date('February 23, 2022'),
		title: 'Fulton County Jail Facilitation',
		location: '',
	},
	{
		allDay: true,
		start: new Date('March 2, 2022 10:00'),
		end: new Date('March 2, 2022'),
		title: 'Fulton County Jail Facilitation',
		location: '',
	},
	{
		allDay: true,
		start: new Date('March 4, 2022 8:00'),
		end: new Date('March 4, 2022'),
		title: 'PTSA MLK High Community Sponsor',
		location: '',
	},
	{
		allDay: true,
		start: new Date('March 19, 2022 11:00'),
		end: new Date('March 19, 2022'),
		title: 'POH Community Distribution',
		location: '',
	},
	{
		allDay: true,
		start: new Date('April 8, 2022'),
		end: new Date('April 8, 2022'),
		title: 'Extended Stay Job Workshop',
		location: '',
	},
	{
		allDay: false,
		start: new Date('July 2, 2021'),
		end: new Date('July 2, 2021'),
		title: 'Extended Stay Job Workshop',
		location: '',
	},
	{
		allDay: true,
		start: new Date('July 16, 2021'),
		end: new Date('July 16, 2021'),
		title: 'Extended Stay Job Workshop',
		location: '',
	},
	{
		allDay: true,
		start: new Date('July 24, 2021'),
		end: new Date('July 24, 2021'),
		title: 'School Supply Distribution ',
		location: '',
	},
	{
		allDay: true,
		start: new Date('July 30, 2021'),
		end: new Date('July 30, 2021'),
		title: 'Extended Stay Job Workshop ',
		location: '',
	},
	{
		allDay: true,
		start: new Date('December 18, 2021'),
		end: new Date('December 18, 2021'),
		title: 'Christmas Holiday Gift Distribution',
		location: '',
	},
	{
		allDay: true,
		start: new Date('June 22, 2021'),
		end: new Date('June 22, 2021'),
		title: 'Food Distribution Ray of Hope Christian Church',
		location: '',
	},
];